### ISSUE TITLE
Getting location on front-end(react) components.

### ISSUE THREAD

**Issue by SalahAdDin** [seididieci/capacitor-backround-geolocation#8]
I'm new using **capacitor** and **ionic** to create mobile applications, hence I have problems understanding the _background_ service workflow.

We need to get the device current location and render a marker with this location in a map; right now what we are doing is to bring the service to the foreground and add a listener which dispatch and action:
```tsx
  useEffect(() => {
    geoLocationService.goForeground()

    geoLocationService.getLocation((location) => {
      // TODO: don't send if the position is the same
      if (location) setDeliveryManLocation({
        id: 0,
        name: "Me",
        lat: location.latitude,
        lng: location.longitude,
      })
    })
  }, [])
```

But we are not sure about this is the correct way to do that.

What's about a hook or a way to do this through the plugin itself?

Thanks.

**Comment by seididieci** [comment]
HI, when I say "background golocation" I mean the ability to receive location updates when the main APP is running in the background (eg. user presses the home button when the app is running). 

Calling the the plugin's method `goForeground ` means that the android service who is resposible of location updates will start working as a foreground service. Android make this visible to the user adding a "fixed" notificaton that you can customize a little through `initialize` plugin method. This will keep your application live and you will still get updates registering for the event.

To make your APP working with location (and make it visible on a map) you can follow the [README](../) and put your logic inside the 'onLocation' listner.

**Comment by SalahAdDin** [comment]
Do you have any example about getting data from the background? I mean, what should I put in the logic?

I removed the `goForeground`(it is not required) function and it does work if i add the listener from the component. Is it a good practice?

**Comment by seididieci** [comment]
Usually I keep the logic in a specific "location" service and update the data (vuex in my specific case) so that all componets that need it get updated. In the meantime, if you need to keep user tracking you can send it to your API(s) using an XHTTPRequest...
You can also use location to give to the user some feedback (eg. a localnotification when he's near a POI) also when the phone is locked.

If you can control when your component is created/destroyed you can also set the listner inside when created and remove when destroyed (just to avoid memory leak), So I think you can have as many listners you want/need and all will be notified about locations.

The `goForeground` method is here only if you want to force the service to run in foreground (that will create the notification also when your app is running on top) but it will (should) always go foreground automatically when your app will go in the background.

If youn don't need location updates when your app Is in background (no need to track user positions or some other logic) I think you can go with the capacitor's own geolocation plugin.

**Comment by SalahAdDin** [comment]
So, what i understand it i'm doing right when i add the listener from my component.
Thanks.
In the future i would like to create a tutorial in order to give examples about this plugin.
